name: horizon_cooler
description: "Horizon Cooler Command Center"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.3
  firebase_core: ^3.6.0
  firebase_database: ^11.1.5
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
